import bcrypt from "bcryptjs";

const hashedPassword = bcrypt.hashSync("123456", 10);

export const companyData = [
  {
    name: "TechFlow Solutions",
    email: "hr@techflow.co.th",
    password: hashedPassword,
    phone: "0212345678",
    address: "Sukhumvit Road, Bangkok, Thailand",
  },
  {
    name: "Digital Marketing Pro",
    email: "careers@digitalmarketingpro.com",
    password: hashedPassword,
    phone: "0223456789",
    address: "Silom Complex, Bangkok, Thailand",
  },
  {
    name: "Bangkok General Hospital",
    email: "recruitment@bgh.co.th",
    password: hashedPassword,
    phone: "0234567890",
    address: "New Petchburi Road, Bangkok, Thailand",
  },
  {
    name: "CP All Public Company",
    email: "hr@cpall.co.th",
    password: hashedPassword,
    phone: "0256789012",
    address: "Lat Phrao Road, Bangkok, Thailand",
  },
  {
    name: "Agoda Company",
    email: "talent@agoda.com",
    password: hashedPassword,
    phone: "0267890123",
    address: "Phaya Thai Road, Bangkok, Thailand",
  },
  {
    name: "True Corporation",
    email: "careers@true.co.th",
    password: hashedPassword,
    phone: "0278901234",
    address: "Ratchathewi, Bangkok, Thailand",
  },
  {
    name: "Central Group",
    email: "jobs@central.co.th",
    password: hashedPassword,
    phone: "0289012345",
    address: "Ploenchit Road, Bangkok, Thailand",
  },
  {
    name: "Kasikorn Bank",
    email: "recruitment@kasikornbank.com",
    password: hashedPassword,
    phone: "0290123456",
    address: "Rat Burana Road, Bangkok, Thailand",
  },
  {
    name: "PTT Public Company",
    email: "careers@pttplc.com",
    password: hashedPassword,
    phone: "0201234567",
    address: "Viphavadi Rangsit Road, Bangkok, Thailand",
  },
  {
    name: "Shopee Thailand",
    email: "th-careers@shopee.com",
    password: hashedPassword,
    phone: "0212345679",
    address: "Chamchuri Square, Bangkok, Thailand",
  },
  {
    name: "Lazada Thailand",
    email: "careers@lazada.co.th",
    password: hashedPassword,
    phone: "0223456780",
    address: "Asok Road, Bangkok, Thailand",
  },
  {
    name: "King Power Group",
    email: "hr@kingpower.com",
    password: hashedPassword,
    phone: "0234567891",
    address: "Rangnam Road, Bangkok, Thailand",
  },
  {
    name: "Thai Airways",
    email: "careers@thaiairways.com",
    password: hashedPassword,
    phone: "0245678902",
    address: "Vibhavadi Rangsit Road, Bangkok, Thailand",
  },
  {
    name: "Siam Cement Group",
    email: "jobs@scg.com",
    password: hashedPassword,
    phone: "0256789013",
    address: "Rama IV Road, Bangkok, Thailand",
  },
  {
    name: "DTAC TriNet",
    email: "careers@dtac.co.th",
    password: hashedPassword,
    phone: "0301234567",
    address: "Chamchuri Square, Phaya Thai, Bangkok, Thailand",
  },
  {
    name: "AIS Thailand",
    email: "jobs@ais.co.th",
    password: hashedPassword,
    phone: "0312345678",
    address: "Paholyothin Road, Chatuchak, Bangkok, Thailand",
  },
  {
    name: "Grab Thailand",
    email: "careers-th@grab.com",
    password: hashedPassword,
    phone: "0323456789",
    address: "Empire Tower, Sathorn Road, Bangkok, Thailand",
  },
  {
    name: "LINE Company Thailand",
    email: "careers@linecorp.com",
    password: hashedPassword,
    phone: "0334567890",
    address: "Gaysorn Tower, Ploenchit Road, Bangkok, Thailand",
  },
  {
    name: "Bangkok Bank",
    email: "recruitment@bbl.co.th",
    password: hashedPassword,
    phone: "0356789012",
    address: "Silom Road, Bang Rak, Bangkok, Thailand",
  },
  {
    name: "Bumrungrad Hospital",
    email: "careers@bumrungrad.com",
    password: hashedPassword,
    phone: "0367890123",
    address: "Sukhumvit Road, Wattana, Bangkok, Thailand",
  },
  {
    name: "Siriraj Hospital",
    email: "hr@siriraj.ac.th",
    password: hashedPassword,
    phone: "0378901234",
    address: "Wang Thonglang, Bangkok Noi, Bangkok, Thailand",
  },
  {
    name: "KPMG Thailand",
    email: "careers@kpmg.co.th",
    password: hashedPassword,
    phone: "0389012345",
    address: "Empire Tower, Sathorn Road, Bangkok, Thailand",
  },
  {
    name: "Deloitte Thailand",
    email: "thcareers@deloitte.com",
    password: hashedPassword,
    phone: "0390123456",
    address: "CRC Tower, Ploenchit Road, Bangkok, Thailand",
  },
  {
    name: "Accenture Thailand",
    email: "careers@accenture.com",
    password: hashedPassword,
    phone: "0301234568",
    address: "Park Ventures Ecoplex, Ploenchit Road, Bangkok, Thailand",
  },
  {
    name: "IBM Thailand",
    email: "careers@ibm.com",
    password: hashedPassword,
    phone: "0312345679",
    address: "Sathorn Square Office Tower, Sathorn Road, Bangkok, Thailand",
  },
  {
    name: "Oracle Thailand",
    email: "careers@oracle.com",
    password: hashedPassword,
    phone: "0323456780",
    address: "The Offices at CentralWorld, Pathumwan, Bangkok, Thailand",
  },
  {
    name: "Microsoft Thailand",
    email: "careers@microsoft.com",
    password: hashedPassword,
    phone: "0334567891",
    address: "Sindhorn Building Tower 3, Ploenchit Road, Bangkok, Thailand",
  },
  {
    name: "Google Thailand",
    email: "careers@google.com",
    password: hashedPassword,
    phone: "0345678902",
    address: "Abdulrahim Place, Rama IV Road, Bangkok, Thailand",
  },
  {
    name: "Amazon Thailand",
    email: "careers@amazon.com",
    password: hashedPassword,
    phone: "0356789013",
    address: "Park Ventures Ecoplex, Ploenchit Road, Bangkok, Thailand",
  },
  {
    name: "Foodpanda Thailand",
    email: "careers@foodpanda.co.th",
    password: hashedPassword,
    phone: "0367890124",
    address: "The Offices at CentralWorld, Pathumwan, Bangkok, Thailand",
  },
  {
    name: "Kerry Express Thailand",
    email: "careers@kerryexpress.com",
    password: hashedPassword,
    phone: "0378901235",
    address: "Sukhumvit Road, Khlong Toei, Bangkok, Thailand",
  },
  {
    name: "DHL Thailand",
    email: "careers@dhl.co.th",
    password: hashedPassword,
    phone: "0389012346",
    address: "Grand Amarin Tower, Ploenchit Road, Bangkok, Thailand",
  },
  {
    name: "FedEx Thailand",
    email: "careers@fedex.com",
    password: hashedPassword,
    phone: "0390123457",
    address: "Q House Lumpini, Sathorn Road, Bangkok, Thailand",
  },
  {
    name: "Robinson Department Store",
    email: "hr@robinson.co.th",
    password: hashedPassword,
    phone: "0412345678",
    address: "Sukhumvit Road, Khlong Toei, Bangkok, Thailand",
  },
  {
    name: "Index Living Mall",
    email: "careers@indexlivingmall.com",
    password: hashedPassword,
    phone: "0423456789",
    address: "Rama IV Road, Pathumwan, Bangkok, Thailand",
  },
  {
    name: "Power Buy",
    email: "jobs@powerbuy.co.th",
    password: hashedPassword,
    phone: "0434567890",
    address: "Ratchadapisek Road, Din Daeng, Bangkok, Thailand",
  },
  {
    name: "HomePro",
    email: "recruitment@homepro.co.th",
    password: hashedPassword,
    phone: "0445678901",
    address: "Phahonyothin Road, Chatuchak, Bangkok, Thailand",
  },
  {
    name: "Watsons Thailand",
    email: "careers@watsons.co.th",
    password: hashedPassword,
    phone: "0456789012",
    address: "Ploenchit Road, Pathumwan, Bangkok, Thailand",
  },
  {
    name: "Boots Thailand",
    email: "hr@boots.co.th",
    password: hashedPassword,
    phone: "0467890123",
    address: "Silom Road, Bang Rak, Bangkok, Thailand",
  },
  {
    name: "Pizza Hut Thailand",
    email: "careers@pizzahut.co.th",
    password: hashedPassword,
    phone: "0478901234",
    address: "Phra Ram II Road, Bang Khun Thian, Bangkok, Thailand",
  },
  {
    name: "KFC Thailand",
    email: "jobs@kfc.co.th",
    password: hashedPassword,
    phone: "0489012345",
    address: "Lat Phrao Road, Chatuchak, Bangkok, Thailand",
  },
  {
    name: "McDonald's Thailand",
    email: "careers@mcdonalds.co.th",
    password: hashedPassword,
    phone: "0490123456",
    address: "Sukhumvit Road, Wattana, Bangkok, Thailand",
  },
  {
    name: "Starbucks Thailand",
    email: "careers@starbucks.co.th",
    password: hashedPassword,
    phone: "0401234568",
    address: "Central World, Pathumwan, Bangkok, Thailand",
  },
  {
    name: "Minor Food Group",
    email: "hr@minorfood.com",
    password: hashedPassword,
    phone: "0412345679",
    address: "Ploenchit Road, Pathumwan, Bangkok, Thailand",
  },
  {
    name: "Siam Commercial Bank",
    email: "recruitment@scb.co.th",
    password: hashedPassword,
    phone: "0423456780",
    address: "Ratchadapisek Road, Chatuchak, Bangkok, Thailand",
  },
  {
    name: "Krungsri Bank",
    email: "careers@krungsri.com",
    password: hashedPassword,
    phone: "0434567891",
    address: "Sathorn Road, Bang Rak, Bangkok, Thailand",
  },
  {
    name: "Government Savings Bank",
    email: "hr@gsb.or.th",
    password: hashedPassword,
    phone: "0445678902",
    address: "Phaya Thai Road, Ratchathewi, Bangkok, Thailand",
  },
  {
    name: "Thai Red Cross Society",
    email: "careers@redcross.or.th",
    password: hashedPassword,
    phone: "0456789013",
    address: "Henri Dunant Road, Pathumwan, Bangkok, Thailand",
  },
  {
    name: "Department of Land Transport",
    email: "hr@dlt.go.th",
    password: hashedPassword,
    phone: "0467890124",
    address: "Phahonyothin Road, Chatuchak, Bangkok, Thailand",
  },
  {
    name: "Bangkok Metropolitan Administration",
    email: "jobs@bangkok.go.th",
    password: hashedPassword,
    phone: "0478901235",
    address: "Din So Road, Dusit, Bangkok, Thailand",
  },
  {
    name: "CAT Telecom",
    email: "hr@cat.co.th",
    password: hashedPassword,
    phone: "0490123457",
    address: "Chaeng Watthana Road, Laksi, Bangkok, Thailand",
  },
  {
    name: "Central Pattana PCL",
    email: "careers@centralpattana.co.th",
    password: hashedPassword,
    phone: "0501234567",
    address: "Central World, Rajdamri Road, Bangkok, Thailand",
  },
  {
    name: "S&P Restaurant Group",
    email: "hr@snp.co.th",
    password: hashedPassword,
    phone: "0512345678",
    address: "Huai Khwang District, Bangkok, Thailand",
  },
  {
    name: "Double A Paper",
    email: "careers@doublea.co.th",
    password: hashedPassword,
    phone: "0523456789",
    address: "Bang Na District, Bangkok, Thailand",
  },
  {
    name: "Major Cineplex Group",
    email: "jobs@majorcineplex.com",
    password: hashedPassword,
    phone: "0534567890",
    address: "Ratchayothin Avenue, Bangkok, Thailand",
  },
  {
    name: "Saha Group",
    email: "recruitment@sahagroup.com",
    password: hashedPassword,
    phone: "0545678901",
    address: "Phetchaburi Road, Bangkok, Thailand",
  },
  {
    name: "BTS Group Holdings",
    email: "careers@btsgroup.co.th",
    password: hashedPassword,
    phone: "0556789012",
    address: "Phaya Thai Road, Bangkok, Thailand",
  },
  {
    name: "Thammasat University",
    email: "hr@tu.ac.th",
    password: hashedPassword,
    phone: "0567890123",
    address: "Rangsit Campus, Pathum Thani, Thailand",
  },
  {
    name: "Chulalongkorn University",
    email: "careers@chula.ac.th",
    password: hashedPassword,
    phone: "0578901234",
    address: "Phaya Thai Road, Bangkok, Thailand",
  },
  {
    name: "Bangkok Airways",
    email: "recruitment@bangkokair.com",
    password: hashedPassword,
    phone: "0589012345",
    address: "Vibhavadi Rangsit Road, Bangkok, Thailand",
  },
  {
    name: "Icon Siam",
    email: "jobs@iconsiam.com",
    password: hashedPassword,
    phone: "0590123456",
    address: "Charoen Nakhon Road, Bangkok, Thailand",
  },
  {
    name: "Emporium Department Store",
    email: "hr@emporium.co.th",
    password: hashedPassword,
    phone: "0501234568",
    address: "Sukhumvit Road, Bangkok, Thailand",
  },
  {
    name: "Tops Supermarket",
    email: "careers@tops.co.th",
    password: hashedPassword,
    phone: "0512345679",
    address: "Ploenchit Road, Bangkok, Thailand",
  },
  {
    name: "Villa Market",
    email: "jobs@villamarket.com",
    password: hashedPassword,
    phone: "0523456780",
    address: "Thonglor District, Bangkok, Thailand",
  },
  {
    name: "Fitness First Thailand",
    email: "careers@fitnessfirst.co.th",
    password: hashedPassword,
    phone: "0534567891",
    address: "Asok Junction, Bangkok, Thailand",
  },
  {
    name: "Anytime Fitness Thailand",
    email: "jobs@anytimefitness.co.th",
    password: hashedPassword,
    phone: "0545678902",
    address: "Ekkamai District, Bangkok, Thailand",
  },
  {
    name: "SF Cinema City",
    email: "recruitment@sfcinemacity.com",
    password: hashedPassword,
    phone: "0556789013",
    address: "MBK Center, Bangkok, Thailand",
  },
  {
    name: "True Coffee",
    email: "careers@truecoffee.co.th",
    password: hashedPassword,
    phone: "0567890124",
    address: "Siam Square, Bangkok, Thailand",
  },
  {
    name: "After You Dessert Cafe",
    email: "hr@afteryou.co.th",
    password: hashedPassword,
    phone: "0578901235",
    address: "Thonglor District, Bangkok, Thailand",
  },
  {
    name: "Oishi Group",
    email: "jobs@oishi.co.th",
    password: hashedPassword,
    phone: "0589012346",
    address: "Lat Phrao District, Bangkok, Thailand",
  },
  {
    name: "CP Fresh Mart",
    email: "careers@cpfreshmart.com",
    password: hashedPassword,
    phone: "0590123457",
    address: "Saphan Phut District, Bangkok, Thailand",
  },
  {
    name: "Charoen Pokphand Foods",
    email: "careers@cpf.co.th",
    password: hashedPassword,
    phone: "0601234567",
    address: "Silom Road, Bang Rak, Bangkok, Thailand",
  },
  {
    name: "Betagro Group",
    email: "hr@betagro.com",
    password: hashedPassword,
    phone: "0612345678",
    address: "Lat Phrao Road, Wang Thonglang, Bangkok, Thailand",
  },
  {
    name: "Toyota Motor Thailand",
    email: "careers@toyota.co.th",
    password: hashedPassword,
    phone: "0623456789",
    address: "Gateway Ekamai, Bangkok, Thailand",
  },
  {
    name: "Honda Automobile Thailand",
    email: "jobs@honda.co.th",
    password: hashedPassword,
    phone: "0634567890",
    address: "Lat Phrao Road, Bangkok, Thailand",
  },
  {
    name: "Samsung Electronics Thailand",
    email: "careers@samsung.com",
    password: hashedPassword,
    phone: "0645678901",
    address: "Rama III Road, Bang Phongphang, Bangkok, Thailand",
  },
  {
    name: "LG Electronics Thailand",
    email: "hr@lge.com",
    password: hashedPassword,
    phone: "0656789012",
    address: "Lat Phrao Road, Bangkok, Thailand",
  },
  {
    name: "Unilever Thailand",
    email: "careers@unilever.com",
    password: hashedPassword,
    phone: "0667890123",
    address: "Lumpini Tower, Rama IV Road, Bangkok, Thailand",
  },
  {
    name: "Nestle Thailand",
    email: "jobs@nestle.co.th",
    password: hashedPassword,
    phone: "0678901234",
    address: "Lat Phrao Road, Bangkok, Thailand",
  },
  {
    name: "Thai Union Group",
    email: "careers@thaiunion.com",
    password: hashedPassword,
    phone: "0689012345",
    address: "Vibhavadi Rangsit Road, Bangkok, Thailand",
  },
  {
    name: "Siam Makro",
    email: "recruitment@makro.co.th",
    password: hashedPassword,
    phone: "0690123456",
    address: "Lat Phrao Road, Bangkok, Thailand",
  },
  {
    name: "Lotus's (Tesco Lotus)",
    email: "careers@lotuss.com",
    password: hashedPassword,
    phone: "0601234568",
    address: "Ratchadapisek Road, Bangkok, Thailand",
  },
  {
    name: "Big C Extra",
    email: "hr@bigcextra.co.th",
    password: hashedPassword,
    phone: "0612345679",
    address: "Saphan Phut, Bangkok, Thailand",
  },
  {
    name: "Fashion Island",
    email: "jobs@fashionisland.co.th",
    password: hashedPassword,
    phone: "0623456780",
    address: "Ram Inthra Road, Bangkok, Thailand",
  },
  {
    name: "Future Park Rangsit",
    email: "careers@futurepark.co.th",
    password: hashedPassword,
    phone: "0634567891",
    address: "Phahonyothin Road, Pathum Thani, Thailand",
  },
  {
    name: "Se-ed Book Center",
    email: "hr@se-ed.com",
    password: hashedPassword,
    phone: "0645678902",
    address: "Huai Khwang, Bangkok, Thailand",
  },
  {
    name: "B2S (Books, Toys, Stationery)",
    email: "careers@b2s.co.th",
    password: hashedPassword,
    phone: "0656789013",
    address: "Siam Paragon, Bangkok, Thailand",
  },
  {
    name: "Office Mate",
    email: "jobs@officemate.co.th",
    password: hashedPassword,
    phone: "0667890124",
    address: "Lat Phrao Road, Bangkok, Thailand",
  },
  {
    name: "Thai Post EMS",
    email: "careers@thailandpost.co.th",
    password: hashedPassword,
    phone: "0678901235",
    address: "Charoenkrung Road, Bangkok, Thailand",
  },
  {
    name: "Flash Express",
    email: "hr@flashexpress.co.th",
    password: hashedPassword,
    phone: "0689012346",
    address: "Bang Sue District, Bangkok, Thailand",
  },
  {
    name: "J&T Express Thailand",
    email: "careers@jtexpress.co.th",
    password: hashedPassword,
    phone: "0690123457",
    address: "Huai Khwang District, Bangkok, Thailand",
  },
];
