export const districts = [
  {
    districtCode: 101,
    districtNameEn: "Phra Nakhon",
    districtNameTh: "พระนคร",
  },
  { districtCode: 102, districtNameEn: "Dusit", districtNameTh: "ดุสิต" },
  { districtCode: 103, districtNameEn: "Nong Chok", districtNameTh: "หนองจอก" },
  { districtCode: 104, districtNameEn: "Bang Rak", districtNameTh: "บางรัก" },
  { districtCode: 105, districtNameEn: "Bang Khen", districtNameTh: "บางเขน" },
  { districtCode: 106, districtNameEn: "Bang Kapi", districtNameTh: "บางกะปิ" },
  {
    districtCode: 107,
    districtNameEn: "Pathum Wan",
    districtNameTh: "ปทุมวัน",
  },
  {
    districtCode: 108,
    districtNameEn: "Pom Prap Sattru Phai",
    districtNameTh: "ป้อมปราบศัตรูพ่าย",
  },
  {
    districtCode: 109,
    districtNameEn: "Phra Khanong",
    districtNameTh: "พระโขนง",
  },
  { districtCode: 110, districtNameEn: "Min Buri", districtNameTh: "มีนบุรี" },
  {
    districtCode: 111,
    districtNameEn: "Lat Krabang",
    districtNameTh: "ลาดกระบัง",
  },
  { districtCode: 112, districtNameEn: "Yan Nawa", districtNameTh: "ยานนาวา" },
  {
    districtCode: 113,
    districtNameEn: "Samphanthawong",
    districtNameTh: "สัมพันธวงศ์",
  },
  { districtCode: 114, districtNameEn: "Phaya Thai", districtNameTh: "พญาไท" },
  { districtCode: 115, districtNameEn: "Thon Buri", districtNameTh: "ธนบุรี" },
  {
    districtCode: 116,
    districtNameEn: "Bangkok Yai",
    districtNameTh: "บางกอกใหญ่",
  },
  {
    districtCode: 117,
    districtNameEn: "Huai Khwang",
    districtNameTh: "ห้วยขวาง",
  },
  {
    districtCode: 118,
    districtNameEn: "Khlong San",
    districtNameTh: "คลองสาน",
  },
  {
    districtCode: 119,
    districtNameEn: "Taling Chan",
    districtNameTh: "ตลิ่งชัน",
  },
  {
    districtCode: 120,
    districtNameEn: "Bangkok Noi",
    districtNameTh: "บางกอกน้อย",
  },
  {
    districtCode: 121,
    districtNameEn: "Bang Khun Thian",
    districtNameTh: "บางขุนเทียน",
  },
  {
    districtCode: 122,
    districtNameEn: "Phasi Charoen",
    districtNameTh: "ภาษีเจริญ",
  },
  {
    districtCode: 123,
    districtNameEn: "Nong Khaem",
    districtNameTh: "หนองแขม",
  },
  {
    districtCode: 124,
    districtNameEn: "Rat Burana",
    districtNameTh: "ราษฎร์บูรณะ",
  },
  {
    districtCode: 125,
    districtNameEn: "Bang Phlat",
    districtNameTh: "บางพลัด",
  },
  { districtCode: 126, districtNameEn: "Din Daeng", districtNameTh: "ดินแดง" },
  { districtCode: 127, districtNameEn: "Bueng Kum", districtNameTh: "บึงกุ่ม" },
  { districtCode: 128, districtNameEn: "Sathon", districtNameTh: "สาทร" },
  { districtCode: 129, districtNameEn: "Bang Sue", districtNameTh: "บางซื่อ" },
  { districtCode: 130, districtNameEn: "Chatuchak", districtNameTh: "จตุจักร" },
  {
    districtCode: 131,
    districtNameEn: "Bang Kho Laem",
    districtNameTh: "บางคอแหลม",
  },
  { districtCode: 132, districtNameEn: "Prawet", districtNameTh: "ประเวศ" },
  {
    districtCode: 133,
    districtNameEn: "Khlong Toei",
    districtNameTh: "คลองเตย",
  },
  {
    districtCode: 134,
    districtNameEn: "Suan Luang",
    districtNameTh: "สวนหลวง",
  },
  { districtCode: 135, districtNameEn: "Chom Thong", districtNameTh: "จอมทอง" },
  {
    districtCode: 136,
    districtNameEn: "Don Mueang",
    districtNameTh: "ดอนเมือง",
  },
  {
    districtCode: 137,
    districtNameEn: "Ratchathewi",
    districtNameTh: "ราชเทวี",
  },
  {
    districtCode: 138,
    districtNameEn: "Lat Phrao",
    districtNameTh: "ลาดพร้าว",
  },
  { districtCode: 139, districtNameEn: "Watthana", districtNameTh: "วัฒนา" },
  { districtCode: 140, districtNameEn: "Bang Khae", districtNameTh: "บางแค" },
  { districtCode: 141, districtNameEn: "Lak Si", districtNameTh: "หลักสี่" },
  { districtCode: 142, districtNameEn: "Sai Mai", districtNameTh: "สายไหม" },
  {
    districtCode: 143,
    districtNameEn: "Khan Na Yao",
    districtNameTh: "คันนายาว",
  },
  {
    districtCode: 144,
    districtNameEn: "Saphan Sung",
    districtNameTh: "สะพานสูง",
  },
  {
    districtCode: 145,
    districtNameEn: "Wang Thonglang",
    districtNameTh: "วังทองหลาง",
  },
  {
    districtCode: 146,
    districtNameEn: "Khlong Sam Wa",
    districtNameTh: "คลองสามวา",
  },
  { districtCode: 147, districtNameEn: "Bang Na", districtNameTh: "บางนา" },
  {
    districtCode: 148,
    districtNameEn: "Thawi Watthana",
    districtNameTh: "ทวีวัฒนา",
  },
  { districtCode: 149, districtNameEn: "Bang Bon", districtNameTh: "บางบอน" },
  {
    districtCode: 150,
    districtNameEn: "Bang Bamru",
    districtNameTh: "บางบำหรุ",
  },
];
