export const provinces = [
  {
    id: 1,
    provinceCode: 10,
    provinceNameEn: "Bangkok",
    provinceNameTh: "กรุงเทพมหานคร",
    profile_id: 1,
  },
  {
    id: 2,
    provinceCode: 11,
    provinceNameEn: "Samut Prakan",
    provinceNameTh: "สมุทรปราการ",
    profile_id: 1,
  },
  {
    id: 3,
    provinceCode: 12,
    provinceNameEn: "Nonthaburi",
    provinceNameTh: "นนทบุรี",
    profile_id: 1,
  },
  {
    id: 4,
    provinceCode: 13,
    provinceNameEn: "Pathum Thani",
    provinceNameTh: "ปทุมธานี",
    profile_id: 1,
  },
  {
    id: 5,
    provinceCode: 14,
    provinceNameEn: "Phra Nakhon Si Ayutthaya",
    provinceNameTh: "พระนครศรีอยุธยา",
    profile_id: 1,
  },
  {
    id: 6,
    provinceCode: 15,
    provinceNameEn: "Ang Thong",
    provinceNameTh: "อ่างทอง",
    profile_id: 1,
  },
  {
    id: 7,
    provinceCode: 16,
    provinceNameEn: "Loburi",
    provinceNameTh: "ลพบุรี",
    profile_id: 1,
  },
  {
    id: 8,
    provinceCode: 17,
    provinceNameEn: "Sing Buri",
    provinceNameTh: "สิงห์บุรี",
    profile_id: 1,
  },
  {
    id: 9,
    provinceCode: 18,
    provinceNameEn: "Chai Nat",
    provinceNameTh: "ชัยนาท",
    profile_id: 1,
  },
  {
    id: 10,
    provinceCode: 19,
    provinceNameEn: "Saraburi",
    provinceNameTh: "สระบุรี",
    profile_id: 1,
  },
  {
    id: 11,
    provinceCode: 20,
    provinceNameEn: "Chon Buri",
    provinceNameTh: "ชลบุรี",
    profile_id: 1,
  },
  {
    id: 12,
    provinceCode: 21,
    provinceNameEn: "Rayong",
    provinceNameTh: "ระยอง",
    profile_id: 1,
  },
  {
    id: 13,
    provinceCode: 22,
    provinceNameEn: "Chanthaburi",
    provinceNameTh: "จันทบุรี",
    profile_id: 1,
  },
  {
    id: 14,
    provinceCode: 23,
    provinceNameEn: "Trat",
    provinceNameTh: "ตราด",
    profile_id: 1,
  },
  {
    id: 15,
    provinceCode: 24,
    provinceNameEn: "Chachoengsao",
    provinceNameTh: "ฉะเชิงเทรา",
    profile_id: 1,
  },
  {
    id: 16,
    provinceCode: 25,
    provinceNameEn: "Prachin Buri",
    provinceNameTh: "ปราจีนบุรี",
    profile_id: 1,
  },
  {
    id: 17,
    provinceCode: 26,
    provinceNameEn: "Nakhon Nayok",
    provinceNameTh: "นครนายก",
    profile_id: 1,
  },
  {
    id: 18,
    provinceCode: 27,
    provinceNameEn: "Sa Kaeo",
    provinceNameTh: "สระแก้ว",
    profile_id: 1,
  },
  {
    id: 19,
    provinceCode: 30,
    provinceNameEn: "Nakhon Ratchasima",
    provinceNameTh: "นครราชสีมา",
    profile_id: 1,
  },
  {
    id: 20,
    provinceCode: 31,
    provinceNameEn: "Buri Ram",
    provinceNameTh: "บุรีรัมย์",
    profile_id: 1,
  },
  {
    id: 21,
    provinceCode: 32,
    provinceNameEn: "Surin",
    provinceNameTh: "สุรินทร์",
    profile_id: 1,
  },
  {
    id: 22,
    provinceCode: 33,
    provinceNameEn: "Si Sa Ket",
    provinceNameTh: "ศรีสะเกษ",
    profile_id: 1,
  },
  {
    id: 23,
    provinceCode: 34,
    provinceNameEn: "Ubon Ratchathani",
    provinceNameTh: "อุบลราชธานี",
    profile_id: 1,
  },
  {
    id: 24,
    provinceCode: 35,
    provinceNameEn: "Yasothon",
    provinceNameTh: "ยโสธร",
    profile_id: 1,
  },
  {
    id: 25,
    provinceCode: 36,
    provinceNameEn: "Chaiyaphum",
    provinceNameTh: "ชัยภูมิ",
    profile_id: 1,
  },
  {
    id: 26,
    provinceCode: 37,
    provinceNameEn: "Amnat Charoen",
    provinceNameTh: "อำนาจเจริญ",
    profile_id: 1,
  },
  {
    id: 27,
    provinceCode: 38,
    provinceNameEn: "Bueng Kan",
    provinceNameTh: "บึงกาฬ",
    profile_id: 1,
  },
  {
    id: 28,
    provinceCode: 39,
    provinceNameEn: "Nong Bua Lam Phu",
    provinceNameTh: "หนองบัวลำภู",
    profile_id: 1,
  },
  {
    id: 29,
    provinceCode: 40,
    provinceNameEn: "Khon Kaen",
    provinceNameTh: "ขอนแก่น",
    profile_id: 1,
  },
  {
    id: 30,
    provinceCode: 41,
    provinceNameEn: "Udon Thani",
    provinceNameTh: "อุดรธานี",
    profile_id: 1,
  },
  {
    id: 31,
    provinceCode: 42,
    provinceNameEn: "Loei",
    provinceNameTh: "เลย",
    profile_id: 1,
  },
  {
    id: 32,
    provinceCode: 43,
    provinceNameEn: "Nong Khai",
    provinceNameTh: "หนองคาย",
    profile_id: 1,
  },
  {
    id: 33,
    provinceCode: 44,
    provinceNameEn: "Maha Sarakham",
    provinceNameTh: "มหาสารคาม",
    profile_id: 1,
  },
  {
    id: 34,
    provinceCode: 45,
    provinceNameEn: "Roi Et",
    provinceNameTh: "ร้อยเอ็ด",
    profile_id: 1,
  },
  {
    id: 35,
    provinceCode: 46,
    provinceNameEn: "Kalasin",
    provinceNameTh: "กาฬสินธุ์",
    profile_id: 1,
  },
  {
    id: 36,
    provinceCode: 47,
    provinceNameEn: "Sakon Nakhon",
    provinceNameTh: "สกลนคร",
    profile_id: 1,
  },
  {
    id: 37,
    provinceCode: 48,
    provinceNameEn: "Nakhon Phanom",
    provinceNameTh: "นครพนม",
    profile_id: 1,
  },
  {
    id: 38,
    provinceCode: 49,
    provinceNameEn: "Mukdahan",
    provinceNameTh: "มุกดาหาร",
    profile_id: 1,
  },
  {
    id: 39,
    provinceCode: 50,
    provinceNameEn: "Chiang Mai",
    provinceNameTh: "เชียงใหม่",
    profile_id: 1,
  },
  {
    id: 40,
    provinceCode: 51,
    provinceNameEn: "Lamphun",
    provinceNameTh: "ลำพูน",
    profile_id: 1,
  },
  {
    id: 41,
    provinceCode: 52,
    provinceNameEn: "Lampang",
    provinceNameTh: "ลำปาง",
    profile_id: 1,
  },
  {
    id: 42,
    provinceCode: 53,
    provinceNameEn: "Uttaradit",
    provinceNameTh: "อุตรดิตถ์",
    profile_id: 1,
  },
  {
    id: 43,
    provinceCode: 54,
    provinceNameEn: "Phrae",
    provinceNameTh: "แพร่",
    profile_id: 1,
  },
  {
    id: 44,
    provinceCode: 55,
    provinceNameEn: "Nan",
    provinceNameTh: "น่าน",
    profile_id: 1,
  },
  {
    id: 45,
    provinceCode: 56,
    provinceNameEn: "Phayao",
    provinceNameTh: "พะเยา",
    profile_id: 1,
  },
  {
    id: 46,
    provinceCode: 57,
    provinceNameEn: "Chiang Rai",
    provinceNameTh: "เชียงราย",
    profile_id: 1,
  },
  {
    id: 47,
    provinceCode: 58,
    provinceNameEn: "Mae Hong Son",
    provinceNameTh: "แม่ฮ่องสอน",
    profile_id: 1,
  },
  {
    id: 48,
    provinceCode: 60,
    provinceNameEn: "Nakhon Sawan",
    provinceNameTh: "นครสวรรค์",
    profile_id: 1,
  },
  {
    id: 49,
    provinceCode: 61,
    provinceNameEn: "Uthai Thani",
    provinceNameTh: "อุทัยธานี",
    profile_id: 1,
  },
  {
    id: 50,
    provinceCode: 62,
    provinceNameEn: "Kamphaeng Phet",
    provinceNameTh: "กำแพงเพชร",
    profile_id: 1,
  },
  {
    id: 51,
    provinceCode: 63,
    provinceNameEn: "Tak",
    provinceNameTh: "ตาก",
    profile_id: 1,
  },
  {
    id: 52,
    provinceCode: 64,
    provinceNameEn: "Sukhothai",
    provinceNameTh: "สุโขทัย",
    profile_id: 1,
  },
  {
    id: 53,
    provinceCode: 65,
    provinceNameEn: "Phitsanulok",
    provinceNameTh: "พิษณุโลก",
    profile_id: 1,
  },
  {
    id: 54,
    provinceCode: 66,
    provinceNameEn: "Phichit",
    provinceNameTh: "พิจิตร",
    profile_id: 1,
  },
  {
    id: 55,
    provinceCode: 67,
    provinceNameEn: "Phetchabun",
    provinceNameTh: "เพชรบูรณ์",
    profile_id: 1,
  },
  {
    id: 56,
    provinceCode: 70,
    provinceNameEn: "Ratchaburi",
    provinceNameTh: "ราชบุรี",
    profile_id: 1,
  },
  {
    id: 57,
    provinceCode: 71,
    provinceNameEn: "Kanchanaburi",
    provinceNameTh: "กาญจนบุรี",
    profile_id: 1,
  },
  {
    id: 58,
    provinceCode: 72,
    provinceNameEn: "Suphan Buri",
    provinceNameTh: "สุพรรณบุรี",
    profile_id: 1,
  },
  {
    id: 59,
    provinceCode: 73,
    provinceNameEn: "Nakhon Pathom",
    provinceNameTh: "นครปฐม",
    profile_id: 1,
  },
  {
    id: 60,
    provinceCode: 74,
    provinceNameEn: "Samut Sakhon",
    provinceNameTh: "สมุทรสาคร",
    profile_id: 1,
  },
  {
    id: 61,
    provinceCode: 75,
    provinceNameEn: "Samut Songkhram",
    provinceNameTh: "สมุทรสงคราม",
    profile_id: 1,
  },
  {
    id: 62,
    provinceCode: 76,
    provinceNameEn: "Phetchaburi",
    provinceNameTh: "เพชรบุรี",
    profile_id: 1,
  },
  {
    id: 63,
    provinceCode: 77,
    provinceNameEn: "Prachuap Khiri Khan",
    provinceNameTh: "ประจวบคีรีขันธ์",
    profile_id: 1,
  },
  {
    id: 64,
    provinceCode: 80,
    provinceNameEn: "Nakhon Si Thammarat",
    provinceNameTh: "นครศรีธรรมราช",
    profile_id: 1,
  },
  {
    id: 65,
    provinceCode: 81,
    provinceNameEn: "Krabi",
    provinceNameTh: "กระบี่",
    profile_id: 1,
  },
  {
    id: 66,
    provinceCode: 82,
    provinceNameEn: "Phangnga",
    provinceNameTh: "พังงา",
    profile_id: 1,
  },
  {
    id: 67,
    provinceCode: 83,
    provinceNameEn: "Phuket",
    provinceNameTh: "ภูเก็ต",
    profile_id: 1,
  },
  {
    id: 68,
    provinceCode: 84,
    provinceNameEn: "Surat Thani",
    provinceNameTh: "สุราษฎร์ธานี",
    profile_id: 1,
  },
  {
    id: 69,
    provinceCode: 85,
    provinceNameEn: "Ranong",
    provinceNameTh: "ระนอง",
    profile_id: 1,
  },
  {
    id: 70,
    provinceCode: 86,
    provinceNameEn: "Chumphon",
    provinceNameTh: "ชุมพร",
    profile_id: 1,
  },
  {
    id: 71,
    provinceCode: 90,
    provinceNameEn: "Songkhla",
    provinceNameTh: "สงขลา",
    profile_id: 1,
  },
  {
    id: 72,
    provinceCode: 91,
    provinceNameEn: "Satun",
    provinceNameTh: "สตูล",
    profile_id: 1,
  },
  {
    id: 73,
    provinceCode: 92,
    provinceNameEn: "Trang",
    provinceNameTh: "ตรัง",
    profile_id: 1,
  },
  {
    id: 74,
    provinceCode: 93,
    provinceNameEn: "Phatthalung",
    provinceNameTh: "พัทลุง",
    profile_id: 1,
  },
  {
    id: 75,
    provinceCode: 94,
    provinceNameEn: "Pattani",
    provinceNameTh: "ปัตตานี",
    profile_id: 1,
  },
  {
    id: 76,
    provinceCode: 95,
    provinceNameEn: "Yala",
    provinceNameTh: "ยะลา",
    profile_id: 1,
  },
  {
    id: 77,
    provinceCode: 96,
    provinceNameEn: "Narathiwat",
    provinceNameTh: "นราธิวาส",
    profile_id: 1,
  },
];
